### ISSUE TITLE
Feature: Execute 'aws sso login' when cached token is expired

### ISSUE THREAD

**Issue by blagerweij** [flyinprogrammer/aws-sso-fetcher#4]
Currently the sso-fetcher fails when the expiration-date of the cached token has passed. Could we execute a process to run `aws sso login --profile xxxx` when that happens, instead of printing an error message ?

**Comment by benkehoe** [comment]
This works today on [aws-sso-credential-process](https://github.com/benkehoe/aws-sso-credential-process) without needing the AWS CLI installed. I think it's a useful feature to have.

However, there is a problem with this when run on a headless system; `credential_process` captures stdout and stderr, so the URL and code that are printed out for use when the browser popup fails don't appear to the user.

So I've made it opt-in, the user has to set the env var `AWS_SSO_INTERACTIVE_AUTH` or the `.aws/config` field `sso_interactive_auth` to `true` or `1`.

**Comment by flyinprogrammer** [comment]
so how would/does this work exactly? i have some random java process running in the background of my laptop that's using my sso aws creds, the sso creds expire, and then magically my browser opens out of no where, and I go do the auth flow again?

it looks like right now you're relying on an oidc client provided in botocore? https://github.com/benkehoe/aws-sso-credential-process/blob/master/aws_sso_credential_process/utils.py#L104

I presume we'd need a similar client in golang because it doesn't seem like our sdk provides one? (certainly not a show stopper)

**Comment by benkehoe** [comment]
That's why it needs to be opt-in. If a user knows that they want to do it, they can enable it, but it's off by default. But yeah, this is how a lot of existing `credential_process` helpers work, except they prompt the user inline rather than dispatching to a browser.

As for how, I like @blagerweij's suggestion. Just dispatch a subprocess for `aws sso login`, which then does the work. I use the code from the CLI in mine because it's Python anyway and then I don't have a dependency on the CLI being installed, but for this it seems like a decent solution. Again it's off by default, so they don't need the CLI installed unless they want this feature.

**Comment by flyinprogrammer** [comment]
https://github.com/99designs/aws-vault/pull/549

apparently the v1 sdk has an oidc provider,  and apparently we might be able to stop using this garbage i wrote and use this real tool that does things much better.

**Comment by flyinprogrammer** [comment]
i would recommend switching over to https://github.com/99designs/aws-vault/releases v6.0.0-beta5 -- it does all this an so much more.

https://github.com/99designs/aws-vault/blob/v6.0.0-beta5/USAGE.md#using-credential-helper
